package dungeons.gui;

import Class.Dungeon;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 * Esta clase representa la selección de personajes en una interfaz de usuario de un juego.
 * @author Santiago Jiménez
 * @author Daniel Felipe Lopez
 * @version 1.0.2
 */
public class CharacterSelection extends javax.swing.JFrame {

    /**
     * El nombre del tipo de caballero seleccionado por el usuario.
     * Este campo se inicializa a null y se espera que se le asigne un valor cuando el usuario seleccione un caballero.
     */
    private String knight = null;

    /**
     * El nivel anteriormente seleccionado por el usuario.
     * Este campo se inicializa a null y se espera que se le asigne un valor cuando el usuario seleccione un nivel.
     */
    private String level = null; 
    
    /**
     * Constructor de la clase CharacterSelection.
     * Inicializa los componentes de la interfaz de usuario.
     */
    public CharacterSelection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barbarian = new javax.swing.JButton();
        magician = new javax.swing.JButton();
        swordMan = new javax.swing.JButton();
        tank = new javax.swing.JButton();
        assasin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        back = new javax.swing.JButton();
        archer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jknight = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        barbarian.setBackground(new java.awt.Color(0, 0, 0));
        barbarian.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        barbarian.setForeground(new java.awt.Color(153, 153, 0));
        barbarian.setText("Barbarian");
        barbarian.setBorder(null);
        barbarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barbarianActionPerformed(evt);
            }
        });

        magician.setBackground(new java.awt.Color(0, 0, 0));
        magician.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        magician.setForeground(new java.awt.Color(153, 153, 0));
        magician.setText("Magician");
        magician.setBorder(null);
        magician.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                magicianActionPerformed(evt);
            }
        });

        swordMan.setBackground(new java.awt.Color(0, 0, 0));
        swordMan.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        swordMan.setForeground(new java.awt.Color(153, 153, 0));
        swordMan.setText("Swordman");
        swordMan.setBorder(null);
        swordMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swordManActionPerformed(evt);
            }
        });

        tank.setBackground(new java.awt.Color(0, 0, 0));
        tank.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        tank.setForeground(new java.awt.Color(153, 153, 0));
        tank.setText("Tank");
        tank.setBorder(null);
        tank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tankActionPerformed(evt);
            }
        });

        assasin.setBackground(new java.awt.Color(0, 0, 0));
        assasin.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        assasin.setForeground(new java.awt.Color(153, 153, 0));
        assasin.setText("Assasin");
        assasin.setBorder(null);
        assasin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assasinActionPerformed(evt);
            }
        });

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jTextArea1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTextArea1);

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        back.setForeground(new java.awt.Color(153, 153, 0));
        back.setText("Back");
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        archer.setBackground(new java.awt.Color(0, 0, 0));
        archer.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        archer.setForeground(new java.awt.Color(153, 153, 0));
        archer.setText("Archer");
        archer.setBorder(null);
        archer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archerActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/CharacterSelection.png"))); // NOI18N

        jknight.setBackground(new java.awt.Color(0, 0, 0));
        jknight.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jknight.setForeground(new java.awt.Color(153, 153, 0));
        jknight.setBorder(null);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 0));
        jButton1.setText("Start");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jknight, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(back)
                            .addComponent(jButton1))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(swordMan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(magician))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(assasin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(barbarian))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tank, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(archer, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jknight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(barbarian, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(archer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(assasin, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                            .addComponent(tank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(swordMan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(magician, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(back)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

        MenuPrincipal menu = new MenuPrincipal();
        menu.setType(getKnight());
        menu.setSize(587, 492);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void archerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archerActionPerformed
        ImageIcon nuevaImagen = new ImageIcon("Archer.png");
        jLabel1.setIcon(nuevaImagen);
        jknight.setText("Archer");
        setKnight(jknight.getText());
    }//GEN-LAST:event_archerActionPerformed

    private void barbarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barbarianActionPerformed
        ImageIcon nuevaImagen = new ImageIcon("Barbarian.png");
        jLabel1.setIcon(nuevaImagen);
        jknight.setText("Barbarian");
        //jTextArea1.append();
        setKnight(jknight.getText());
    }//GEN-LAST:event_barbarianActionPerformed

    private void assasinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assasinActionPerformed
        ImageIcon nuevaImagen = new ImageIcon("Assasin.png");
        jLabel1.setIcon(nuevaImagen);
        jknight.setText("Assasin");
        setKnight(jknight.getText());
    }//GEN-LAST:event_assasinActionPerformed

    private void tankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tankActionPerformed
        ImageIcon nuevaImagen = new ImageIcon("Tank.png");
        jLabel1.setIcon(nuevaImagen);
        jknight.setText("Tank");
        setKnight(jknight.getText());
    }//GEN-LAST:event_tankActionPerformed

    private void swordManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swordManActionPerformed
        ImageIcon nuevaImagen = new ImageIcon("Swordman.png");
        jLabel1.setIcon(nuevaImagen);
        jknight.setText("SwordMan");
        setKnight(jknight.getText());
    }//GEN-LAST:event_swordManActionPerformed

    private void magicianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_magicianActionPerformed
        ImageIcon nuevaImagen = new ImageIcon("Magician.png");
        jLabel1.setIcon(nuevaImagen);
        jknight.setText("Magician");
        setKnight(jknight.getText());
        
    }//GEN-LAST:event_magicianActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Dungeon map = new Dungeon(0, 0, 700, 800, getKnight(),level );
        Game gameMap = new Game(map);
        map.setDrawable(gameMap);
        gameMap.setSize(700, 800);
        gameMap.setVisible(true); 
        try {
            PlayerSoundPrincipal player = new PlayerSoundPrincipal("Medievalmusic.wav");
            new Thread(player).start();
        } catch (IOException ex) {
            Logger.getLogger(CharacterSelection.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton archer;
    private javax.swing.JButton assasin;
    private javax.swing.JButton back;
    private javax.swing.JButton barbarian;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jknight;
    private javax.swing.JButton magician;
    private javax.swing.JButton swordMan;
    private javax.swing.JButton tank;
    // End of variables declaration//GEN-END:variables

    /**
 * Obtiene el valor de 'knight'.
 * @return El valor actual del atributo 'knight'.
 */
public String getKnight() {
    return knight;
}

/**
 * Asigna un valor para el atributo 'knight'.
 * @param knight El nuevo valor para el atributo 'knight'.
 */
public void setKnight(String knight) {
    this.knight = knight;
}

/**
 * Obtiene el valor del atributo 'level'.
 * @return El valor actual del atributo 'level'.
 */
public String getLevel() {
    return level;
}

/**
 * Asigna un valor para el atributo 'level'.
 * @param level El nuevo valor para el atributo 'level'.
 */
public void setLevel(String level) {
    this.level = level;
}
}
